### ISSUE TITLE
Can not install, got error when applying db tables migration

### ISSUE THREAD

**Issue by sanjarbek** [robregonm/yii2-auth#1]
Can not install, got error when applying db tables migration. Please, help with detailed instructions.
These are console outputs.
$ yii migrate/up --migrationPath=@auth/migrations
Yii Migration Tool (based on Yii v2.0.0-dev)

Total 2 new migrations to be applied:
    m000000_000001_CreateRbacTables
    m000000_000002_CreateUserTables

Apply the above migrations? (yes|no) [no]:yes
**\* applying m000000_000001_CreateRbacTables
    > execute SQL: /**
- Database schema required by \yii\rbac\DbManager.
  *
- @author Qiang Xue qiang.xue@gmail.com
- @author Alexander Kochetov creocoder@gmail.com
- @link http://www.yiiframework.com/
- @copyright 2008 Yii Software LLC
- @license http://www.yiiframework.com/license/
- @since 2.0
  */

drop table if exists `auth_assignment` ... done (time: 0.001s)
    > execute SQL:
drop table if exists `auth_item_child` ... done (time: 0.001s)
    > execute SQL:
drop table if exists `auth_item` ... done (time: 0.001s)
    > execute SQL:

create table `auth_item`
(
   `name`                 varchar(64) not null,
   `type`                 integer not null,
   `description`          text,
   `biz_rule`              text,
   `data`                 text,
   primary key (`name`),
   key `type` (`type`)
) engine InnoDB ... done (time: 0.447s)
    > execute SQL:

create table `auth_item_child`
(
   `parent`               varchar(64) not null,
   `child`                varchar(64) not null,
   primary key (`parent`,`child`),
   foreign key (`parent`) references `auth_item` (`name`) on delete cascade on u
pdate cascade,
   foreign key (`child`) references `auth_item` (`name`) on delete cascade on up
date cascade
) engine InnoDB ... done (time: 0.399s)
    > execute SQL:

create table `auth_assignment`
(
   `item_name`            varchar(64) not null,
   `user_id`              integer not null,
   `biz_rule`              text,
   `data`                 text,
   primary key (`item_name`,`user_id`),
   foreign key (`item_name`) references `auth_item` (`name`) on delete cascade o
n update cascade
) engine InnoDB ... done (time: 0.243s)
**\* applied m000000_000001_CreateRbacTables (time: 1.144s)

**\* applying m000000_000002_CreateUserTables
Exception: Trying to get property of non-object (D:\vhosts\helpdesk\vendor\robre
gonm\yii2-auth\migrations\m000000_000002_CreateUserTables.php:9)
#0 D:\vhosts\helpdesk\vendor\yiisoft\yii2\console\controllers\MigrateController.

php(513): yii\db\Migration->up()
#1 D:\vhosts\helpdesk\vendor\yiisoft\yii2\console\controllers\MigrateController.

**Comment by ik-j** [comment]
thanks @giovannyc28.
