### ISSUE TITLE
Exception 'yii\db\Exception' with message 'could not find driver'

### ISSUE THREAD

**Issue by techsdi** [robregonm/yii2-auth#32]
Saludos Ingeniero.

Estoy tratando de instalar tu extensión, sin embargo cuando trato de correr la rutina de actualizacion de la base de datos con el comando yii migrate/up --migrationPath=@auth/migrations aparece el error anterior.

Estoy trabajando con una base de datos postgresql bajo Windows con el entorno de desarrollo WAMP.

**Comment by wahono77** [comment]
This problem is from your phpcli.ini instead of php.ini. in your phpcli.ini you should add :

extension=php_pdo_mysql.dll

as in php.ini

**Comment by yuriEfin** [comment]
apt-get install php5-mysql
