### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nitrok** [robregonm/yii2-auth#36]
Try to install on yii2 fresh installation, basic template. 

> composer require robregonm/yii2-auth "dev-master"
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for robregonm/yii2-auth dev-master -> satisfiable by robregonm/yii2-auth[dev-master].
    - robregonm/yii2-auth dev-master requires yiisoft/yii2-swiftmailer dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by pv123** [comment]
Hi, i have the same error:
Invalid Parameter – yii\base\InvalidParamException
The view file does not exist: C:\wamp\www\site\views\layouts\/homepage.php
How to fix it?
Thanks.
Regards
