### ISSUE TITLE
migration errors

### ISSUE THREAD

**Issue by martrix78** [robregonm/yii2-auth#38]
*\* applying m000000_000001_CreateRbacTables
Exception: Unknown component ID: authManager (/var/www/weekendtrip/vendor/yiisoft/yii2/di/ServiceLocator.php:136)

on console config needs add this:
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
        ],

**Comment by wmfunk** [comment]
+1 i have added in may console.php
```
components' => [
....		
'authManager' => [
			'class' => 'yii\rbac\DbManager',
		],
...
```

run this 
php yii migrate/up --migrationPath=@auth/migrations

and became error 
 
Exception: Unknown component ID: authManager (/var/www/jeantailor/vendor/yiisoft/yii2/di/ServiceLocator.php:136)

thank you for support....!
