### ISSUE TITLE
run yii migrate have error

### ISSUE THREAD

**Issue by djfly** [robregonm/yii2-auth#5]
Welcome to Git (version 1.8.1.2-preview20130201)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
dsf@DSF-PC ~
$ cd d:/xampp/htdocs/a
dsf@DSF-PC /d/xampp/htdocs/a
$ php yii migrate/up --migrationPath=@auth/migrations
Yii Migration Tool (based on Yii v2.0.0-dev)

Total 2 new migrations to be applied:
    m000000_000001_CreateRbacTables
    m000000_000002_CreateUserTables

Apply the above migrations? (yes|no) [no]:yes
**\* applying m000000_000001_CreateRbacTables
Exception: Unknown component ID: authManager (D:\xampp\htdocs\a\vendor\yiisoft\y
ii2\di\ServiceLocator.php:135)
#0 D:\xampp\htdocs\a\vendor\robregonm\yii2-auth\migrations\m000000_000001_Create

RbacTables.php(14): yii\di\ServiceLocator->get('authManager')
#1 D:\xampp\htdocs\a\vendor\yiisoft\yii2\db\Migration.php(65): m000000_000001_Cr

eateRbacTables->safeUp()
#2 D:\xampp\htdocs\a\vendor\yiisoft\yii2\console\controllers\MigrateController.p

hp(512): yii\db\Migration->up()
#3 D:\xampp\htdocs\a\vendor\yiisoft\yii2\console\controllers\MigrateController.p

hp(181): yii\console\controllers\MigrateController->migrateUp('m000000_000001_..
.')
#4 [internal function]: yii\console\controllers\MigrateController->actionUp(0)
#5 D:\xampp\htdocs\a\vendor\yiisoft\yii2\base\InlineAction.php(54): call_user_fu

nc_array(Array, Array)
#6 D:\xampp\htdocs\a\vendor\yiisoft\yii2\base\Controller.php(127): yii\base\Inli

neAction->runWithParams(Array)
#7 D:\xampp\htdocs\a\vendor\yiisoft\yii2\console\Controller.php(83): yii\base\Co

ntroller->runAction('up', Array)
#8 D:\xampp\htdocs\a\vendor\yiisoft\yii2\base\Module.php(434): yii\console\Contr

oller->runAction('up', Array)
#9 D:\xampp\htdocs\a\vendor\yiisoft\yii2\console\Application.php(164): yii\base\

Module->runAction('migrate/up', Array)
#10 D:\xampp\htdocs\a\vendor\yiisoft\yii2\console\Application.php(140): yii\cons

ole\Application->runAction('migrate/up', Array)
#11 D:\xampp\htdocs\a\vendor\yiisoft\yii2\base\Application.php(339): yii\console

\Application->handleRequest(Object(yii\console\Request))
#12 D:\xampp\htdocs\a\yii(30): yii\base\Application->run()
#13 {main}

**\* failed to apply m000000_000001_CreateRbacTables (time: 0.124s)

Migration failed. The rest of the migrations are canceled.
dsf@DSF-PC /d/xampp/htdocs/a
$

**Comment by ik-j** [comment]
Here is the solution by: @giovannyc28

**Comment by joepages** [comment]
Hello all, I'm trying to install user RBC without any success in while migrating tables, specifically in the User Tables, any help please?? 

*** applying m000000_000002_CreateUserTables
Exception: Setting unknown property: auth\Module::signupWithEmailOnly (/Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Component.php:197)
#0 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set('signupWithEmail...', false)
#1 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(auth\Module), Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Module.php(138): yii\base\Object->__construct(Array)
#3 [internal function]: yii\base\Module->__construct('auth', Object(yii\console\Application), Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('auth\\Module', Array, Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('auth\\Module', Array, Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Module.php(354): yii\BaseYii::createObject(Array, Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/robregonm/yii2-auth/migrations/m000000_000002_CreateUserTables.php(10): yii\base\Module->getModule('auth')
#9 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/db/Migration.php(81): m000000_000002_CreateUserTables->safeUp()
#10 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): yii\db\Migration->up()
#11 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m000000_000002_...')
#12 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#13 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#15 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('up', Array)
#16 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('up', Array)
#17 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('migrate/up', Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('migrate/up', Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/advance/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#20 /Applications/XAMPP/xamppfiles/htdocs/advance/yii(31): yii\base\Application->run()
#21 {main}
*** failed to apply m000000_000002_CreateUserTables (time: 0.002s)


Migration failed. The rest of the migrations are canceled.
