### ISSUE TITLE
No existen mensajes en español en vista de registro "sign up"

### ISSUE THREAD

**Issue by johnparra** [robregonm/yii2-auth#53]
# Cambios a realizar.
1. Crear mensajes en `messages/es/auth.user.php`

|Variable|Traducción|
|---|---|
|`Sign up`|`Registrarse`|
|`Already registered? Sign in!`|`Ya esta registrado? Ingress aquí!`|

2. Llamar mensajes en el modelo `SignupForm`
```php
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => Yii::t('auth.user', 'Username'),
            'email' => Yii::t('auth.user', 'Email'),
            'password_hash' => Yii::t('auth.user', 'Password Hash'),
            'password_reset_token' => Yii::t('auth.user', 'Password Reset Token'),
            'auth_key' => Yii::t('auth.user', 'Auth Key'),
            'status' => Yii::t('auth.user', 'Status'),
            'last_visit_time' => Yii::t('auth.user', 'Last Visit Time'),
            'create_time' => Yii::t('auth.user', 'Create Time'),
            'update_time' => Yii::t('auth.user', 'Update Time'),
            'delete_time' => Yii::t('auth.user', 'Delete Time'),
        ];
    }
```

3. Llamar mensajes en view `signup`

```php

$this->title = \Yii::t('auth.user', 'Sign up');
...
<?= Html::submitButton(\Yii::t('auth.user', 'Sign up'), ['class' => 'btn btn-success btn-block']) ?>
...
 <?= Html::a(\Yii::t('auth.user', 'Already registered? Sign in!'), ['/auth/default/login']) ?>
```

**Comment by johnparra** [comment]
git push -u origin issue_53
remote: Permission to robregonm/yii2-auth.git denied to johnparra.
fatal: unable to access 'https://github.com/robregonm/yii2-auth.git/': The requested URL returned error: 403

**Comment by robregonm** [comment]
Estimado John, el repositorio no permite hacer push directamente, sino a través de un pull-request realizado desde su propio repositorio.
https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/
y
https://help.github.com/articles/creating-a-pull-request/

Saludos.

**Comment by johnparra** [comment]
Fue realizado el pull-request
